baseurl = "http://billkidwell.com/"
languageCode = "en-us"
title = "Bill Kidwell"
theme = "beautifulhugo"
pygmentsUseClasses = true
disqusShortname = "billkidwellblog"
googleAnalytics = "UA-79823920-1"

[Params]
  logo = "img/Hooding.jpg"
  subtitle = "Software Engineer. Software Craftsman. Lifelong Learner."

[Author]
  name = "Bill Kidwell"
  email = "kidwell.bill+site@gmail.com"
  facebook = "bill.kidwell"
  github = "bill-kidwell"
  twitter = "billyrkidwell"
  linkedin = "in/billkidwell"
  stackoverflow = "2858612/bill-kidwell"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
